### ISSUE TITLE
I can't connect to localhost

### ISSUE THREAD

**Issue by MattCowBoy** [bryanberger/sketch-incopy#1]
Hi, I'm very interested in this plugin. This let me work smarter and better with copywriter. 
I tried using it but it doesn't work. I can't connect to http://localhost:8080.

Does this plugin works with the last version of Sketch?
Thank you very much

**Comment by bryanberger** [comment]
@MattCowBoy Should work now as of this commit: https://github.com/bryanberger/sketch-incopy/commit/dfe8bbf1d4c5ede77687be3eff9eb960158c8c0c

Tested it on Sketch Version 46.2 and it works for me.
